#!/bin/bash

set -eux
set -o pipefail

# Install some needed dependencies for instack-undercloud
sudo yum -y install \
    diskimage-builder \
    openstack-tripleo-image-elements \
    openstack-tripleo-heat-templates \
    openstack-tripleo \
    instack

sudo yum -y install git

# os-cloud-config is broken in Delorean packaging right now, b/c it's missing
# the patch to remove the pbr requirements, yet doesn't actually Require it, so
# just install it manually for now.
sudo yum -y install os-cloud-config
sudo yum -y install python-pbr

# newer openstack-keystone requires python-zope-interface, but that is not
# avaiable anywhere for EL7. So just install the Fedora package for now. We can
# add this dep to Delorean going forward.
if ! rpm -q python-zope-interface; then
    sudo yum install -y http://mirrors.kernel.org/fedora//releases/20/Everything/x86_64/os/Packages/p/python-zope-interface-4.0.5-2.fc20.x86_64.rpm
fi

# pip install hardware for not until python-hardware is packaged
sudo pip install hardware

# tripleo-puppet-elements is not yet in Delorean, so just git clone for now
if [ ! -d "tripleo-puppet-elements" ]; then
    git clone http://git.openstack.org/openstack/tripleo-puppet-elements
else
    echo "WARNING##################################:"
    echo "tripleo-puppet-elements directory already exists, not recloning"
fi

# git clone instack-undercloud since we're not using packages for that yet
if [ ! -d "instack-undercloud" ]; then
    git clone http://github.com/rdo-management/instack-undercloud
else
    echo "WARNING##################################:"
    echo "instack-undercloud directory already exists, not recloning"
fi
