#!/bin/bash

set -eux
set -o pipefail

# Install repo file for Delorean master packages and Delorean el7 midstream packages built from
# rdo-management.
sudo rpm -Uvh http://file.rdu.redhat.com/~rbrady/delorean-release-kilo.0.4-1.git.0.f560b97.noarch.rpm


# Delorean requires RDO
if ! rpm -q rdo-release; then
    sudo yum install -y https://rdo.fedorapeople.org/rdo-release.rpm
fi

if ! rpm -q epel-release; then
    sudo yum install -y http://mirrors.einstein.yu.edu/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
fi

# rhos-release is also required, otherwise we have no base RHEL repositories to
# pull any dependencies from (without using subscription-manager anyway).
sudo rpm -Uvh --force http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
export RUN_RHOS_RELEASE=${RUN_RHOS_RELEASE:-"1"}
if [ "$RUN_RHOS_RELEASE" = "1" ]; then
    sudo rhos-release 6 -d
fi
# Ideally though, we don't want to end up with any RHOS packages installed, so
# we disable the poodle repo.
sudo yum-config-manager --disable rhelosp-6.0-poodle
# We need openwsman-python from the optional repo
sudo yum-config-manager --enable rhelosp-rhel-7-server-opt

sudo yum -y install git

# os-cloud-config is broken in Delorean packaging right now, b/c it's missing
# the patch to remove the pbr requirements, yet doesn't actually Require it, so
# just install it manually for now.
sudo yum -y install os-cloud-config
sudo yum -y install python-pbr

# newer openstack-keystone requires python-zope-interface, but that is not
# avaiable anywhere for EL7. So just install the Fedora package for now. We can
# add this dep to Delorean going forward.
if ! rpm -q python-zope-interface; then
    sudo yum install -y http://mirrors.kernel.org/fedora//releases/20/Everything/x86_64/os/Packages/p/python-zope-interface-4.0.5-2.fc20.x86_64.rpm
fi

# Required for building puppet-based images
sudo yum install -y openstack-heat-templates

# tripleo-puppet-elements is not yet in Delorean, so just git clone for now
if [ ! -d "tripleo-puppet-elements" ]; then
    git clone http://git.openstack.org/openstack/tripleo-puppet-elements
else
    echo "WARNING##################################:"
    echo "tripleo-puppet-elements directory already exists, not recloning"
fi
