#!/bin/bash

set -eux
set -o pipefail

function vm_delete(){
    sudo virsh undefine $1
    sudo virsh destroy $1
}

# delete instack vm and remove its files
vm_delete instack
sudo rm -rf /var/lib/libvirt/images/instack.qcow2
sudo rm -rf /home/stack/instack.qcow2

# delete all of the baremetal vms
for i in $(seq 0 3); do
    vm_delete baremetal_$i
done

