#!/bin/bash

export CPU=1
export MEM=2048
export DISK=30
export ARCH=amd64
export NeutronPublicInterface=eth0
export OVERCLOUD_LIBVIRT_TYPE=qemu
export NETWORK_CIDR=10.0.0.0/8
export FLOATING_IP_START=192.0.2.45
export FLOATING_IP_END=192.0.2.64
export FLOATING_IP_CIDR=192.0.2.0/24
export MACS="52:54:00:46:f5:0f 52:54:00:5e:94:de 52:54:00:7a:3a:17 52:54:00:95:0b:5f"
export COMPUTESCALE=1
export BLOCKSTORAGESCALE=1
export SWIFTSTORAGESCALE=0

